language: node_js
node_js:
    - 'node'

deploy:
    provider: npm
    email: npm.bokub@mail.com
    api_key: $NPM_TOKEN
    on:
        tags: true

after_deploy: curl https://purge.jsdelivr.net/npm/rgb-light-card
